# Generated by Django 4.2.14 on 2024-08-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counted',
            new_name='Contact',
        ),
    ]
