# Generated by Django 4.2.14 on 2024-08-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_datetime',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_datetime',
            new_name='updated_date',
        ),
    ]
